### ISSUE TITLE
General question about hold time files to IPFS (persistence/removing)

### ISSUE THREAD

**Issue by chisNaN** [RTradeLtd/Temporal#363]
Hello

First thanks for the temporal service existence (and efforts involved in it)
Second my topic is not an issue but more about general question about persistence and removing file from IPFS that i hope could be useful to others!

I registered to the temporal ipfs service because I saw the possibility of giving a HOLD TIME parameter when uploading a file to IPFS

I have several questions regarding the following scenario (if i a upload a small file with a minimum 1 month hold time):

- Will the uploaded file be AUTOMATICALLY removed from the temporal public nodes
(without any further actions)?
- If the file is NOT automatically removed from the temporal public nodes, what should i have to accomplish so that it is removed from your nodes?
- Do the file continue to persist and be accessible from other public nodes like infura, cloudflare?
- If so, is it POSSIBLE (in a manner that is not too sophisticated or requiring to communicate with ipfs node admin/engineer) to remove the file from all other public nodes?

Thanks in advance

**Comment by postables** [comment]
Hello thanks for the interest. The github issues are meant specifically for bug reports, or feature requests. However since this question is specific to the publicly available Temporal instance and not  about bug reports or feature requests, I will close the issue in favour of redirecting you to our community  [telegram](https://t.me/RTradeTEMPORAL)  chat where myself or another team member will gladly answer these questions.

Thanks fro your understanding :muscle:

**Comment by chisNaN** [comment]
Thanks for your reply.
I will get in touch with you in telegram
But 
I think I got reply.
There is a page showing delete expiration of ipfs file uploaded to YOUR NODES.
But I read if some other nodes queried the same file thru its hash then it will become available on that node as long as it policy expiration says so and so on if another node queries it again....
