### ISSUE TITLE
Question regarding self destruction of files on IPFS

### ISSUE THREAD

**Issue by chisNaN** [RTradeLtd/Temporal#377]
Hello

Once again thanks for all efforts involved in the temporal services.
I have a new query.
I was wondering HOW is working the "auto destruction" of file uploaded on IPFS.
Here is what i did

1) on 14th october (gmt+1) i uploaded a text file (thru javascript), using a 1 month HOLD TIME value and with the following content
_"uploaded on saturday 14 sept 2019 to ipfs node temporal cloud
and "HOPEFULLY" not request by any other public nodes..."_

2) during this month I NEVER queried the hash of this file (**QmQiWhwamHMZM3wwLvrepyvMhqYAg7GKQW9zV111N5jVpE**) from within any other public nodes like infura or cloudflare

3) today at around 9h30 gmt+1 16th of october (> 1 month later) i tried to fetch the same hash using a javascript download code:

```
const r = await fetch('https://api.temporal.cloud:6767/v2/ipfs/utils/download/QmQiWhwamHMZM3wwLvrepyvMhqYAg7GKQW9zV111N5jVpE', options);
console.warn(await r.text())
```

4) i am still able to retrieve the content of the text file over 1 month hold time expiration!
even tough the file and hash is not listed on the uploads page here https://play.temporal.cloud/uploads

What is the conclusion?

- is it a "normal" behavior
- shall i conclude that when an object is uploaded to temporal ipfs, somehow  a mechanism notifies other public nodes so that the object is spread?

Thanks in advance for the explanations

**Comment by postables** [comment]
No problem, thanks for your interest! So a few different things. We **guarantee** that the data will be pinned on our nodes for the hold time you specify. So in the case of the hash you uploaded, we guarantee that it will be pinned on our nodes for the month.

After the hold time is expired (some times immediately, sometimes a short period after) the item is **removed from your uploads**, at this point in time the data is no longer **guaranteed to be pinned** but it is still available on our iPFS nodes, and may be available for an indeterminate amount of time.  How long exactly? This depends on a wide variety of factors such as:

1) Who else is pinning this data
 * Although you may have not disclosed the hash to someone else, it is still entirely plausible that someone else uploaded or pinned the content with the same hash. In this case we can't remove it from the node because removing it will also removes someone elses data.
  * When you uploaded something to an IPFS node, there is an automatic process by which the node updates the DHT with a *provider record* informing the rest of the network that the node is providing the content. This means that is theoretically plausible for someone to be running a DHT scraper that watches the DHT and pins new data
2) How much storage our nodes are taking up
  * If the storage our nodes use isn't full, and there is still space availalable, then we wont remove any data that isn't being stored by people on Temporal until that storage space is needed. For example say we have 10GB of storage space available, and the object you uploaded was 1KB, until that 1KB of storage is desperately needed we wont remove it.
3) We haven't done a garbage collection on our nodes
  * Actually getting the data removed from the IPFS nodes isn't a process that is exactly "quick". During the garbage collection process the entire node is essentially useless, as there are some race conditions, and overall inefficiencies with the pinning and garbage collection process. As such, the only "safe" way to garbage collect is with a node that is not being used at all. Because our production environment is under regular use, it means we have to either run the garbage collection process during a maintenance period, or in a very strict series of steps.

So what is the conclusion:

* This is normal behavior
* You are **guaranteed** to have the data pinned by our nodes for the duration you specify
* You have an indeterminate amount of time whereby you are granted *free but unreliable* storage of your data until that storage space is reclaimed. You *can't rely on this for storage*, if you want to rely on storage you would need to re-add the data.
* `shall i conclude that when an object is uploaded to temporal ipfs, somehow a mechanism notifies other public nodes so that the object is spread?` this is true for ANY IPFS nodes, not just Temporal. The mechanism is called the ["provider"](https://github.com/ipfs/go-ipfs-provider).

**Comment by chisNaN** [comment]
Well i thanks you for such concise and complete explanation.
Probably i will copy paste it to some of my friends using ipfs.

**Comment by postables** [comment]
Not a problem happy to help :rocket:
