### ISSUE TITLE
uploads page only shows hashes and date

### ISSUE THREAD

**Issue by Clay-Ferguson** [RTradeLtd/Temporal#462]
I was trying to use "https://play.temporal.cloud/uploads" page to troubleshoot an upload to see if it worked, and I'm noticing the only info displayed is the hashes and the actual day of month of the upload.

With all due respect, this is not very useful. Showing the exact time of the upload, the number of bytes, the mime, and and the file size really is he minimum amount of information that would be viable on that page, and probably is pretty trivial to add.

I suggest this page list ALL info that is know about a file, since you already have that in your server and is fairly trivial to add. Knowing just which hashes were uploaded on any given day is somewhat useful, but not for troubleshooting actual real-world issues.

**Comment by bonedaddy** [comment]
As mentioned in the last issue, that website is being deprecated and https://play2.temporal.cloud has the information you are looking for. The previous website is pretty old and hasn't been updated beyond dependency updates in a very long time. It is still technically a very valid web interface to use, but its provided as is, and wont ever be updated.

Also one thing to keep in mind is that if you're using the IPFS HTTP API to use our services, we tend to not capture the filenames and inject that into the database, as we do with when you use Temporal's API. Due to our somewhat atypical requirements of needing to authenticate users, authorize certain calls, parse the IPFS requests to grab information we need to do the administrative related functions all within a reverse proxy, and while making sure any and all clients (both software APIs and cURL) can use the API as if they were talking directly to a IPFS node's API.

Initially when writing this system (called warp) we tried to capture filenames with all relevant API calls. We observed that depending on what client was being used with warp, whether its the js client, golang client, python, `curl` from the command line, etc... the exact format of the messages being sent/back and forth wasn't always the same. For example the first method we tried worked for the go-ipfs-api client, but didnt work for js-ipfs-http-client.

Quite frankly due to how often there are changes with the various clients, and go-ipfs (both intentional and unintentional) we stopped trying to do this. At one point we had it working for go-ipfs-api, and then a new update was made to go-ipfs and it broke the method we were using.  

Our goals for warp were to enable all different clients access to all IPFS HTTP API calls within reason (no pin rm, no pin ls, etc..) in a highly available fashion, while being as close in performance to using  the IPFS HTTP API directly, and satisfying our atypical requirements. We've done that, and more; warp is generaly speaking faster for popular data fetching get calls than as if you were hitting an IPFS HTTP API directly.

In an ideal world we would be able to capture filenames as part of this, but running IPFS in production is not ideal. There's a ton of niche issues due to a variety of factors, and there's some things that require too much investment of time for what the offer to warrant being done.

That being said, using Temporal's API directly we can properly capture all this information easily because it's an API ontop of the IPFS HTTP API, and we can define the API calls as we see fit, and then adding it to IPFS via the IPFS HTTP API.

**Comment by Clay-Ferguson** [comment]
I should've worded my comment in a more positive/constructive way because *Temporal.Cloud* is great and I really love it, and I'm trying to get the word out to other developers about you too. Also your code is running flawlessly and I haven't had any problems whatsoever!

I only started using Temporal two days ago but do already have it built into my upload capability so that users (of quantizr.com) can upload attachments directly to Temporal via Quantizr, and then directly view images, stream video, and audio, etc.

I know what you mean about running IPFS itself in prod. IPFS has had some glitches and nuance for sure. I'm actually running FULL GO-IPFS node on Quantizr, and only integrated Temporal in to let you scale the storage for me. I do have the ability in Quantizr to do everything Temporal is doing for me, but I just don't want to pay Linode for huge storage.

About the https://play2.temporal.cloud site, I had not tried that until a few minutes ago because I didn't understand you to mean it was ready yet, so I stayed on what your website itself points to, but I'll be using the play2 one from now on, and I saw that it *does* have the info I needed!

I appreciate you providing the info that you did.

**Comment by bonedaddy** [comment]
No worries, thanks for the kind words, glad our service can help you scale your nodes :rocket:  Understandable, I probably could've explained better as well that the website was ready.

If there's anything you think can be improved, whether it's a new feature, or changes to existing ones feel free to open a feature request issue. There isn't a guarantee we can implement everything, but there tends to be periods throughout the year where we have a bit extra time on our hands and go through the existing feature requests to see what we can implement.
